# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  #Maintain dependencies for Main NuGet / .NET
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Izzy-MoonbotTests" # Location of package manifests
    schedule:
      interval: "monthly"
    # Prefix all commit messages with "NuGet"
    # include a list of updated dependencies
    commit-message:
      prefix: "NuGet"
      include: "scope"

  #Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Actions"
      include: "scope"

  #Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/Izzy-Moonbot"
    schedule:
      interval: "monthly"
    assignees:
      - "LunarNightShade"
    reviewers:
      - "LunarNightShade"
    commit-message:
      prefix: "Docker"
      include: "scope"
