name: Docker Image CI

on:
  push:
    branches: [ "mane" ]
  workflow_dispatch:

jobs:

  build-and-publish:

    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref_name == 'mane' || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: linux/arm64

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug

    - name: Build the Docker image
      run: docker buildx build . --file ./Izzy-Moonbot/Dockerfile --tag ghcr.io/manechat/izzy-moonbot:latest --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg BUILD_COMMIT=$GITHUB_SHA --platform linux/arm64

    - name: Log in to Container registry
      run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Push image to registry
      run: docker push ghcr.io/manechat/izzy-moonbot:latest
