name: Package Prune

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]
  workflow_dispatch:

jobs:

  package-prune:

    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: GHCR Pruning
      uses: vlaurin/action-ghcr-prune@v0.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: manechat
        container: izzy-moonbot
        dry-run: false
        keep-tags: latest
        prune-untagged: true
