name: Package Prune

on:
  workflow_run:
    workflows: [Docker Image CI]
    types: [completed]
  workflow_dispatch:

jobs:

  package-prune:

    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_dispatch }}

    steps:
    - name: GHCR Pruning
      uses: vlaurin/action-ghcr-prune@v0.4.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: manechat
        container: izzymoonbot
        dry-run: false # Dry-run first, then change to `false`
        keep-tags: latest
        untagged: true
