name: Package Prune

on:
  workflow_run:
    workflows: [Docker Image CI]
    types:
      - completed
  workflow_dispatch:

jobs:

  package-prune:

    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
  - name: Prune
    uses: vlaurin/action-ghcr-prune@main
    with:
      token: ${{ secrets.YOUR_TOKEN }}
      organization: manechat
      container: izzymoonbot
      dry-run: true # Dry-run first, then change to `false`
      keep-tags: latest
      untagged: true